config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flats_path
  end

  def show
  end

  def edit
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  def update
    @flat.update(flat_params)

    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit <%= @flat.name %></h1>
        <div class="mt-3">
          <%= simple_form_for(@flat) do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p>All <%= @flats.length %> flats.</p>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-4 d-flex">
      <div class="flat-card d-flex flex-column">
        <div class="flat-card-image" style="background-image: url(<%= flat.image_link %>);"></div>
        <div class="flat-card-content flex-fill">
          <div>
            <h4><%= flat.name %></h4>
          </div>
          <p><%= flat.address %></p>
          <div class="d-flex">
            <div class="d-flex align-items-center">
              <i class="fas fa-user-friends mr-2"></i>
              <span><%= flat.number_of_guests %></span>
            </div>
            <div class="d-flex ml-3 align-items-center">
              <i class="fas fa-euro-sign mr-2"></i>
              <span><%= flat.price_per_night %></span>
            </div>
          </div>
        </div>
        <div class="flat-card-actions">
          <%= link_to "More info", flat_path(flat)%>
          <%= link_to "Edit", edit_flat_path(flat), class: "ml-3 text-warning"%>
          <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "ml-3 text-danger"%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= simple_form_for(@flat) do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @flat.image_link %>);">
</div>
<div class="container mt-n5">
  <div class="row">
    <div class="col-8 d-flex flex-column">
      <div class="flat-show-content">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="flat-show-content flex-fill">
        <h3>Description</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-content">
        <h5>Book this flat!</h5>
        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-content">
        <h5>Details</h5>
        <div class="d-flex">
          <div class="d-flex align-items-center">
            <i class="fas fa-user-friends mr-2"></i>
            <span><%= @flat.number_of_guests %></span>
          </div>
          <div class="d-flex ml-3 align-items-center">
            <i class="fas fa-euro-sign mr-2"></i>
            <span><%= @flat.price_per_night %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/flats">Simple Airbnb</a>
      <a class="btn btn-outline-primary my-2 my-sm-0 rounded-btn" href="/flats/new">Add a Flat</a>
    </nav>
    <%= yield %>
  </body>
</html>